stages:
  - build
  - test

include:
  - template: Jobs/SAST.gitlab-ci.yml

variables:
  SAST_EXCLUDED_PATHS: "spec, test, tests, tmp, .venv, **/.venv"
  IMAGE_TAR: image.tar

.pipeline_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build-app:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/src"
      --dockerfile "${CI_PROJECT_DIR}/src/Dockerfile"
      --target prod
      --no-push
      --tarPath "${CI_PROJECT_DIR}/${IMAGE_TAR}"
  artifacts:
    paths:
      - ${IMAGE_TAR}
    expire_in: 1 hour
  extends: .pipeline_rules

container-scan:
  stage: test
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  needs:
    - job: build-app
      artifacts: true
  script:
    - trivy image
      --input "${IMAGE_TAR}"
      --severity HIGH,CRITICAL
      --exit-code 1
  extends: .pipeline_rules
