services:
  backend:
    profiles: [debug]
    build:
      context: ./src
      dockerfile: Dockerfile
      target: debug
    ports:
      - "127.0.0.1:${PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      ENV: debug
      PORT: 8000
    volumes:
      - ./src/backend/fourdrinier:/app/backend/fourdrinier
      - ./src/backend/pyproject.toml:/app/backend/pyproject.toml
      - ./src/backend/uv.lock:/app/backend/uv.lock
