apiVersion: v1
kind: Secret
metadata:
  name: fourdrinier-backend-token
  namespace: minecraft
  annotations:
    kubernetes.io/service-account.name: fourdrinier-backend
type: kubernetes.io/service-account-token
