"""initial_revision

Revision ID: 9bb6c74e9d94
Revises: 
Create Date: 2025-12-31 04:14:18.685840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb6c74e9d94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('loader', sa.String(), nullable=False),
    sa.Column('game_version', sa.String(), nullable=False),
    sa.Column('modrinth_projects', sa.JSON(), nullable=True),
    sa.Column('cpu_request', sa.String(), nullable=True),
    sa.Column('cpu_limit', sa.String(), nullable=True),
    sa.Column('memory_request', sa.String(), nullable=True),
    sa.Column('memory_limit', sa.String(), nullable=True),
    sa.Column('pvc_size', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_name'), 'servers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servers_name'), table_name='servers')
    op.drop_table('servers')
    # ### end Alembic commands ###
