"""add_per_server_resources

Revision ID: cd65bbe190a9
Revises: 05ea73ded26e
Create Date: 2025-12-31 03:03:48.120187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd65bbe190a9'
down_revision: Union[str, None] = '05ea73ded26e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('cpu_request', sa.String(), nullable=True))
    op.add_column('servers', sa.Column('cpu_limit', sa.String(), nullable=True))
    op.add_column('servers', sa.Column('memory_request', sa.String(), nullable=True))
    op.add_column('servers', sa.Column('memory_limit', sa.String(), nullable=True))
    op.add_column('servers', sa.Column('pvc_size', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'pvc_size')
    op.drop_column('servers', 'memory_limit')
    op.drop_column('servers', 'memory_request')
    op.drop_column('servers', 'cpu_limit')
    op.drop_column('servers', 'cpu_request')
    # ### end Alembic commands ###
