"""'host rewrite'

Revision ID: 0650701822cd
Revises: 9d1895410782
Create Date: 2026-07-13 22:52:04.294642

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0650701822cd"
down_revision: str | Sequence[str] | None = "9d1895410782"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hosts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "docker", "kubernetes", name="host_type", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("labels", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "type", name="uq_hosts_id_type"),
        sa.UniqueConstraint("name", name="uq_hosts_name"),
    )
    with op.batch_alter_table("hosts", schema=None) as batch_op:
        batch_op.create_index("ix_hosts_enabled", ["enabled"], unique=False)

    op.create_table(
        "docker_host_details",
        sa.Column("host_id", sa.Uuid(), nullable=False),
        sa.Column(
            "host_type",
            sa.Enum("docker", "kubernetes", name="host_type", native_enum=False),
            server_default=sa.text("'docker'"),
            nullable=False,
        ),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("port", sa.Integer(), server_default=sa.text("(22)"), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("keypair_id", sa.Uuid(), nullable=False),
        sa.Column("host_key_type", sa.String(length=64), nullable=True),
        sa.Column("host_key_b64", sa.Text(), nullable=True),
        sa.Column("host_key_fingerprint", sa.String(length=64), nullable=True),
        sa.CheckConstraint("host_type = 'docker'", name="ck_docker_host_details_type"),
        sa.ForeignKeyConstraint(
            ["host_id", "host_type"],
            ["hosts.id", "hosts.type"],
            name="fk_docker_host_details_host",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["keypair_id"], ["ssh_keypairs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("host_id"),
    )
    op.create_table(
        "kubernetes_host_details",
        sa.Column("host_id", sa.Uuid(), nullable=False),
        sa.Column(
            "host_type",
            sa.Enum("docker", "kubernetes", name="host_type", native_enum=False),
            server_default=sa.text("'kubernetes'"),
            nullable=False,
        ),
        sa.Column("api_url", sa.String(length=512), nullable=False),
        sa.Column("ca_cert_pem", sa.Text(), nullable=False),
        sa.Column("token_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column(
            "namespace",
            sa.String(length=63),
            server_default=sa.text("'fourdrinier'"),
            nullable=False,
        ),
        sa.CheckConstraint("host_type = 'kubernetes'", name="ck_kubernetes_host_details_type"),
        sa.ForeignKeyConstraint(
            ["host_id", "host_type"],
            ["hosts.id", "hosts.type"],
            name="fk_kubernetes_host_details_host",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("host_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kubernetes_host_details")
    op.drop_table("docker_host_details")
    with op.batch_alter_table("hosts", schema=None) as batch_op:
        batch_op.drop_index("ix_hosts_enabled")

    op.drop_table("hosts")
    # ### end Alembic commands ###
