"""create kubernetes_hosts table

Revision ID: 9d1895410782
Revises: ec529e6d0d56
Create Date: 2026-07-11 20:36:34.792090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1895410782'
down_revision: Union[str, Sequence[str], None] = 'ec529e6d0d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kubernetes_hosts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_url', sa.String(length=512), nullable=False),
    sa.Column('ca_cert_pem', sa.Text(), nullable=False),
    sa.Column('token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('namespace', sa.String(length=63), server_default=sa.text("'fourdrinier'"), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('labels', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('kubernetes_hosts', schema=None) as batch_op:
        batch_op.create_index('ix_kubernetes_hosts_enabled', ['enabled'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kubernetes_hosts', schema=None) as batch_op:
        batch_op.drop_index('ix_kubernetes_hosts_enabled')

    op.drop_table('kubernetes_hosts')
    # ### end Alembic commands ###
