"""create ssh_keypairs and docker_hosts tables

Revision ID: ec529e6d0d56
Revises: 
Create Date: 2026-07-11 12:46:44.750258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec529e6d0d56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ssh_keypairs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('generated', 'uploaded', name='keypair_source', native_enum=False, length=32), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('private_key_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint'),
    sa.UniqueConstraint('name')
    )
    op.create_table('docker_hosts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), server_default=sa.text('(22)'), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('keypair_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('labels', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('host_key_type', sa.String(length=64), nullable=True),
    sa.Column('host_key_b64', sa.Text(), nullable=True),
    sa.Column('host_key_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['keypair_id'], ['ssh_keypairs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('docker_hosts', schema=None) as batch_op:
        batch_op.create_index('ix_docker_hosts_enabled', ['enabled'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docker_hosts', schema=None) as batch_op:
        batch_op.drop_index('ix_docker_hosts_enabled')

    op.drop_table('docker_hosts')
    op.drop_table('ssh_keypairs')
    # ### end Alembic commands ###
