/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServersIndexRouteImport } from './routes/servers/index'
import { Route as HostsIndexRouteImport } from './routes/hosts/index'
import { Route as ServersNewRouteImport } from './routes/servers/new'
import { Route as ServersServerIdRouteImport } from './routes/servers/$serverId'
import { Route as HostsNewRouteImport } from './routes/hosts/new'
import { Route as HostsHostIdRouteImport } from './routes/hosts/$hostId'

const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIndexRoute = ServersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServersRoute,
} as any)
const HostsIndexRoute = HostsIndexRouteImport.update({
  id: '/hosts/',
  path: '/hosts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersNewRoute = ServersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ServersRoute,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/$serverId',
  path: '/$serverId',
  getParentRoute: () => ServersRoute,
} as any)
const HostsNewRoute = HostsNewRouteImport.update({
  id: '/hosts/new',
  path: '/hosts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsHostIdRoute = HostsHostIdRouteImport.update({
  id: '/hosts/$hostId',
  path: '/hosts/$hostId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/servers': typeof ServersRouteWithChildren
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/hosts/new': typeof HostsNewRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/new': typeof ServersNewRoute
  '/hosts/': typeof HostsIndexRoute
  '/servers/': typeof ServersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/hosts/new': typeof HostsNewRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/new': typeof ServersNewRoute
  '/hosts': typeof HostsIndexRoute
  '/servers': typeof ServersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/servers': typeof ServersRouteWithChildren
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/hosts/new': typeof HostsNewRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/new': typeof ServersNewRoute
  '/hosts/': typeof HostsIndexRoute
  '/servers/': typeof ServersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/servers'
    | '/hosts/$hostId'
    | '/hosts/new'
    | '/servers/$serverId'
    | '/servers/new'
    | '/hosts/'
    | '/servers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hosts/$hostId'
    | '/hosts/new'
    | '/servers/$serverId'
    | '/servers/new'
    | '/hosts'
    | '/servers'
  id:
    | '__root__'
    | '/'
    | '/servers'
    | '/hosts/$hostId'
    | '/hosts/new'
    | '/servers/$serverId'
    | '/servers/new'
    | '/hosts/'
    | '/servers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServersRoute: typeof ServersRouteWithChildren
  HostsHostIdRoute: typeof HostsHostIdRoute
  HostsNewRoute: typeof HostsNewRoute
  HostsIndexRoute: typeof HostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/': {
      id: '/servers/'
      path: '/'
      fullPath: '/servers/'
      preLoaderRoute: typeof ServersIndexRouteImport
      parentRoute: typeof ServersRoute
    }
    '/hosts/': {
      id: '/hosts/'
      path: '/hosts'
      fullPath: '/hosts/'
      preLoaderRoute: typeof HostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/new': {
      id: '/servers/new'
      path: '/new'
      fullPath: '/servers/new'
      preLoaderRoute: typeof ServersNewRouteImport
      parentRoute: typeof ServersRoute
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof ServersRoute
    }
    '/hosts/new': {
      id: '/hosts/new'
      path: '/hosts/new'
      fullPath: '/hosts/new'
      preLoaderRoute: typeof HostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId': {
      id: '/hosts/$hostId'
      path: '/hosts/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof HostsHostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServersRouteChildren {
  ServersServerIdRoute: typeof ServersServerIdRoute
  ServersNewRoute: typeof ServersNewRoute
  ServersIndexRoute: typeof ServersIndexRoute
}

const ServersRouteChildren: ServersRouteChildren = {
  ServersServerIdRoute: ServersServerIdRoute,
  ServersNewRoute: ServersNewRoute,
  ServersIndexRoute: ServersIndexRoute,
}

const ServersRouteWithChildren =
  ServersRoute._addFileChildren(ServersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServersRoute: ServersRouteWithChildren,
  HostsHostIdRoute: HostsHostIdRoute,
  HostsNewRoute: HostsNewRoute,
  HostsIndexRoute: HostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
