/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostsIndexRouteImport } from './routes/hosts/index'
import { Route as HostsNewRouteImport } from './routes/hosts/new'
import { Route as HostsHostIdRouteImport } from './routes/hosts/$hostId'

const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsIndexRoute = HostsIndexRouteImport.update({
  id: '/hosts/',
  path: '/hosts/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsNewRoute = HostsNewRouteImport.update({
  id: '/hosts/new',
  path: '/hosts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsHostIdRoute = HostsHostIdRouteImport.update({
  id: '/hosts/$hostId',
  path: '/hosts/$hostId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/servers': typeof ServersRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/hosts/new': typeof HostsNewRoute
  '/hosts/': typeof HostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/servers': typeof ServersRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/hosts/new': typeof HostsNewRoute
  '/hosts': typeof HostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/servers': typeof ServersRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/hosts/new': typeof HostsNewRoute
  '/hosts/': typeof HostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/servers' | '/hosts/$hostId' | '/hosts/new' | '/hosts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/servers' | '/hosts/$hostId' | '/hosts/new' | '/hosts'
  id:
    '__root__' | '/' | '/servers' | '/hosts/$hostId' | '/hosts/new' | '/hosts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServersRoute: typeof ServersRoute
  HostsHostIdRoute: typeof HostsHostIdRoute
  HostsNewRoute: typeof HostsNewRoute
  HostsIndexRoute: typeof HostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/': {
      id: '/hosts/'
      path: '/hosts'
      fullPath: '/hosts/'
      preLoaderRoute: typeof HostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/new': {
      id: '/hosts/new'
      path: '/hosts/new'
      fullPath: '/hosts/new'
      preLoaderRoute: typeof HostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId': {
      id: '/hosts/$hostId'
      path: '/hosts/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof HostsHostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServersRoute: ServersRoute,
  HostsHostIdRoute: HostsHostIdRoute,
  HostsNewRoute: HostsNewRoute,
  HostsIndexRoute: HostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
